Changed: Nala > APT

diff --git a/primo-di-tutto/scripts/all_up b/primo-di-tutto/scripts/all_up
--- a/primo-di-tutto/scripts/all_up
+++ b/primo-di-tutto/scripts/all_up
@@ -2,9 +2,10 @@
 
 # Upgrade und Aufräumen mit nala und flatpak
 echo -e "\n\n#### APT-Update und -Upgrade #############\n"
-nala upgrade -y || { echo "ERROR: nala upgrade failed."; exit 1; }
+apt update || { echo "ERROR: APT Update failed."; exit 1; }
+apt upgrade -y || { echo "ERROR: APT Upgrade failed."; exit 1; }
 echo -e "\n\n#### APT-Autoremove ######################\n"
-nala autopurge -y || { echo "ERROR: nala autopurge failed."; exit 1; }
+apt autoremove -y || { echo "ERROR: nala autopurge failed."; exit 1; }
 echo -e "\n\n#### Flatpak-Update ######################\n"
 flatpak update -y || { echo "ERROR: flatpak update failed."; exit 1; }
 echo -e "\n\n#### Flatpak-Autoremove ##################\n"
